version: 2.1

orbs:
    node: circleci/node@5.0.0

jobs:
  check_lint:
    working_directory: ~/workspace
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - restore_cache:
          keys:
            - api-deps-{{ checksum "api/yarn.lock" }}
            - webapp-deps-{{ checksum "webapp/yarn.lock" }}
      - run:
          name: Install deps
          command: bin/install-deps.sh
      - save_cache:
          paths:
            - ~/workspace/api/node_modules
          key: api-deps-{{ checksum "api/yarn.lock" }}
      - save_cache:
          paths:
            - ~/workspace/webapp/node_modules
          key: webapp-deps-{{ checksum "webapp/yarn.lock" }}
      - run:
          name: Run Lint checks
          command: bin/check_lint.sh

  test_unit:
    working_directory: ~/workspace
    docker:
      - image: 'cimg/base:stable'
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: "tr_e2e"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - restore_cache:
          keys:
            - api-deps-{{ checksum "api/yarn.lock" }}
            - webapp-deps-{{ checksum "webapp/yarn.lock" }}
      - run:
          name: Install deps
          command: bin/install-deps.sh
      - save_cache:
          paths:
            - ~/workspace/api/node_modules
          key: api-deps-{{ checksum "api/yarn.lock" }}
      - save_cache:
          paths:
            - ~/workspace/webapp/node_modules
          key: webapp-deps-{{ checksum "webapp/yarn.lock" }}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Run tests and checks
          command: bin/test_unit.sh

  test_e2e:
    working_directory: ~/workspace
    docker:
      - image: 'cimg/base:stable'
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: "tr_e2e"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - restore_cache:
          keys:
            - api-deps-{{ checksum "api/yarn.lock" }}
            - webapp-deps-{{ checksum "webapp/yarn.lock" }}
      - run:
          name: Install deps
          command: bin/install-deps.sh
      - save_cache:
          paths:
            - ~/workspace/api/node_modules
          key: api-deps-{{ checksum "api/yarn.lock" }}
      - save_cache:
          paths:
            - ~/workspace/webapp/node_modules
          key: webapp-deps-{{ checksum "webapp/yarn.lock" }}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Run tests and checks
          command: bin/test_e2e.sh

  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - setup_remote_docker
      - run:
          name: Build
          command: RELEASE=$CIRCLE_TAG bin/build-docker.sh

  build_old:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - setup_remote_docker
      - run:
          name: Build
          command: RELEASE=$CIRCLE_TAG bin/build-docker-old.sh

workflows:
  version: 2

  test:
    jobs:
      - check_lint:
           filters:
              branches:
                ignore: master
      - test_unit:
          requires:
            - check_lint
          filters:
              branches:
                ignore: master  
      - test_e2e:
          requires:
            - check_lint
          filters:
              branches:
                ignore: master  

  release:
    jobs:
      - check_lint:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - test_unit:
          requires:
            - check_lint
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - test_e2e:
          requires:
            - check_lint
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - build:
          context: traduora
          requires:
            - check_lint
            - test_unit
            - test_e2e
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - build_old:
          context: traduora
          requires:
            - check_lint
            - test_unit
            - test_e2e
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
